[global]
  checkNewVersion = true

[log]
  level = "INFO"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"
  [entryPoints.https.http.tls]
    certResolver = "letseencrypt"

  [entryPoints.traefik]
    address = ":55555"
  [entryPoints.traefik.http.tls]
    certResolver = "letseencrypt"

[certificatesResolvers.letseencrypt.acme]
  storage = "/acme/acme.json"
  [certificatesResolvers.letseencrypt.acme.tlsChallenge]

[api]
  dashboard = true
#  debug = true
