[global]
  checkNewVersion = true

[log]
  level = "INFO"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http.tls]
    certResolver = "myresolver"

[certificatesResolvers.myresolver.acme]
  storage = "/acme/acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]

[api]
  dashboard = true
#  debug = true